#!/usr/bin/env bash

set -x

# configuration
source configuration


# database
apt -y install mariadb-server python-pymysql

cat << EOF > /etc/mysql/conf.d/openstack.cnf
[client]
default-character-set = utf8

[mysqld]
bind-address = ${IP_PRIVATE['controller1']}
default-storage-engine = innodb
innodb_file_per_table
max_connections = 4096

# charset
character-set-client = utf8
character-set-server = utf8
collation-server = utf8_general_ci
skip-character-set-client-handshake

[mysql]
default-character-set = utf8

EOF

## correct utf8 bug: https://bugs.launchpad.net/openstack-manuals/+bug/1575688
sed -ri "s/utf8mb4/utf8/" /etc/mysql/mariadb.conf.d/*

## remove default bind
sed -i '/^bind-address/d' /etc/mysql/mariadb.conf.d/50-server.cnf

systemctl stop mysql.service
systemctl enable mysql.service
systemctl start mysql.service

## mysql_secure_installation but non-interactive
mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$DATABASE_PASS');"
mysql -u root -e "DELETE FROM mysql.user WHERE User='';"
mysql -u root -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
mysql -u root -e "DROP DATABASE IF EXISTS test;"
mysql -u root -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';"
mysql -u root -e "FLUSH PRIVILEGES;"


# nosql
apt -y install mongodb-server mongodb-clients python-pymongo

sed -ri "s/bind_ip.*$/bind_ip = ${IP_PRIVATE[controller1]}/" /etc/mongodb.conf

echo 'smallfiles = true' >> /etc/mongodb.conf

systemctl stop mongodb.service

rm /var/lib/mongodb/journal/prealloc.*

systemctl enable mongodb.service
systemctl start mongodb.service


# message queue
apt -y install rabbitmq-server

rabbitmqctl add_user openstack $RABBIT_PASS
rabbitmqctl set_permissions openstack ".*" ".*" ".*"


# memcached
apt -y install memcached python-memcache

# this setting, ultimately, will require 127.0.0.1 only. When we install another proxy and a balancer, we will need this.
#sed -ri "s@-l 127.0.0.1@-l $CONTROLLER1_IP_PRIVATE@" /etc/memcached.conf

systemctl enable memcached.service
systemctl restart memcached.service
