#!/usr/bin/env bash

set -x

# configuration
source configuration

# name resolution
cat << EOF > /etc/hosts
127.0.0.1   localhost
127.0.1.1   $( hostname -b )

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters


# OpenStack
EOF

## insert all nodes here
for h in ${!HOSTNAME[@]}; do
    echo ${IP_PRIVATE[$h]} ${h}.${NETWORK_DOMAIN} ${h}
done >> /etc/hosts

# ntp
apt -y install chrony

sed -ri "s/^pool .*$/${CHRONY_POOL}/" /etc/chrony/chrony.conf

systemctl stop chrony.service
systemctl enable chrony.service
systemctl start chrony.service

# packages
apt install software-properties-common
add-apt-repository cloud-archive:mitaka

apt -y update
apt -y dist-upgrade

apt -y install python-openstackclient
