#!/usr/bin/env bash

source ${HOME}/openstack-credentials/admin-openrc


# params
username=${1}
auth_url=http://os.zrh.cloudsigma.com:5000/v3
identity_api_version=3
image_api_version=2
password=$( apg -M CLN -m 30 -n 1 )
project_description="${username^} Project"
project_domain_name=default
project_name="${username,,}-project"
user_domain_name=default


# test
## check if username was provided
if [[ -z $username ]]; then
    echo 'You need to provide a username as a parameter.'
    exit 1
elif [[ "$username" == 'admin' || "$username" == 'swift' ]]; then
    echo 'You cannot create the admin or swift users with this script.'
    exit 2
elif [[ -f ${HOME}/openstack-credentials/${username}-openrc ]]; then
    echo "$username already exists. Please, delete the user manually on OpenStack and, then, delete the credential file."
    exit 3
fi


# do
openstack project create --domain $project_domain_name --description "$project_description" $project_name
openstack user create --domain $project_domain_name --password $password $username
openstack role add --project $project_name --user $username user


## write the credentials down
cat << EOF > ${HOME}/openstack-credentials/${username}-openrc
export OS_PROJECT_DOMAIN_NAME=$project_domain_name
export OS_USER_DOMAIN_NAME=$user_domain_name
export OS_PROJECT_NAME="$project_name"
export OS_USERNAME=$username
export OS_PASSWORD=$password
export OS_AUTH_URL=$auth_url
export OS_IDENTITY_API_VERSION=$identity_api_version
export OS_IMAGE_API_VERSION=$image_api_version
EOF

## show t hem
source ${HOME}/openstack-credentials/${username}-openrc

cat << EOF
Done!

The user's info is stored in ~/openstack-credentials/${username}-openrc.

The info is as follows:

OS_PROJECT_DOMAIN_NAME:     $OS_PROJECT_DOMAIN_NAME
OS_USER_DOMAIN_NAME:        $OS_USER_DOMAIN_NAME
OS_PROJECT_NAME:            $OS_PROJECT_NAME
OS_USERNAME:                $OS_USERNAME
OS_PASSWORD:                $OS_PASSWORD
OS_AUTH_URL:                $OS_AUTH_URL
OS_IDENTITY_API_VERSION:    $OS_IDENTITY_API_VERSION
OS_IMAGE_API_VERSION:       $OS_IMAGE_API_VERSION

EOF

