#!/usr/bin/env bash

# check if apg is installed
if ! hash apg &> /dev/null; then
    echo 'You, first, need to install apg to generate the passwords'
    exit 1
fi


# do
vars=(
    DATABASE_PASS
    ADMIN_PASS
    CEILOMETER_DBPASS
    CEILOMETER_PASS
    CINDER_DBPASS
    CINDER_PASS
    DASH_DBPASS
    DEMO_PASS
    GLANCE_DBPASS
    GLANCE_PASS
    HEAT_DBPASS
    HEAT_DOMAIN_PASS
    HEAT_PASS
    KEYSTONE_DBPASS
    KEYSTONE_PASS
    NEUTRON_DBPASS
    NEUTRON_PASS
    NOVA_DBPASS
    NOVA_PASS
    RABBIT_PASS
    SWIFT_PASS
)

passwords=()
while read password; do
    passwords+=( $password )
done < <( apg -M CLN -m 30 -n 20 )

for ((i=0; i < ${#vars[@]}; ++i )); do
    printf "%s=%s\n" "${vars[i]}" "${passwords[i]}"
done
